### ISSUE TITLE
Link/app not working, maybe another link

### ISSUE THREAD

**Issue by kitmacleod** [arup-group/social-data#6]
[Impressive work and article](https://blog.streamlit.io/open-source-eviction-data/), with this link (does not work for me on Chrome or FF) maybe you meant to use this link https://share.streamlit.io/arup-group/eviction-data/run.py.

**Comment by jstock29** [comment]
Yes that link is old. Please use [https://share.streamlit.io/arup-group/social-data/run.py]( https://share.streamlit.io/arup-group/social-data/run.py). Do you know where that link was posted so I can change it?

**Comment by jstock29** [comment]
Found it and updated the README. Let me know if any other links use the old repository name. Thanks!
